config/routes.rb
DigMenu::Application.routes.draw do

  devise_for :users

  namespace :api do
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
      delete 'users/sign_out' => 'sessions#destroy'
    end

    resources :recipes do
      member do
        post '/vote_up' => 'recipes#vote_up'
      end
    end
  end

  resources :users do
    member do
      get :following, :followers, :liked_recipes, :liked_restaurants
    end
  end

  resources :followships,  :only => [:create, :destroy]

  get "admin/show"

  resources :restaurants do
    member do
      get '/recipes' => 'restaurants#show_recipes'
      get '/users_upvoted' => 'restaurants#show_users_upvoted'
      post '/vote_up' => 'restaurants#vote_up'
    end
  end
  
  resources :recipes do
    member do
      post '/like' => 'recipes#vote_up'
      get '/users_upvoted' => 'recipes#show_users_upvoted'      
      post '/vote_up' => 'recipes#vote_up'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :restaurant_id, :description
  attr_accessible :recipe_images_attributes
  attr_accessible :category_list, :alert_list, :taste_list

  belongs_to :restaurant

  acts_as_votable
  acts_as_taggable
  acts_as_taggable_on :tags, :category, :alert, :taste

  validates :name, :presence => true

  has_many :recipe_images, :dependent => :destroy

  has_many :taggings, :as => :taggable, :dependent => :destroy, :include => :tag, 
          :class_name => "ActsAsTaggableOn::Tagging",
          :conditions => "taggings.taggable_type = 'Recipe'"
          
  #for context-dependent tags:
  has_many :category_tags, :through => :taggings, :source => :tag, :class_name => "ActsAsTaggableOn::Tag",
          :conditions => "taggings.context = 'category'"
  has_many :alert_tags, :through => :taggings, :source => :tag, :class_name => "ActsAsTaggableOn::Tag",
          :conditions => "taggings.context = 'alert'"
  has_many :taste_tags, :through => :taggings, :source => :tag, :class_name => "ActsAsTaggableOn::Tag",
          :conditions => "taggings.context = 'taste'"

  # default per_page                   
  paginates_per 10

  accepts_nested_attributes_for :recipe_images, :reject_if => proc { |attributes| attributes['photo'].blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :category_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :alert_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :taste_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true

  #, :reject_if => lambda { |r| r['recipe_image'].nil? }
  
  def avatar_url
    return recipe_images[0].photo_small_url if recipe_images
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # Render mobile or desktop depending on User-Agent for these actions.
  before_filter :check_for_mobile

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.search(params[:q]).page(params[:page]).per(params[:perPage])

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @recipes}
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @restaurant = @recipe.restaurant

    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @recipe}
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @recipe = Recipe.new
    3.times {@recipe.recipe_images.build} # added this

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    #3.times {@recipe.recipe_images.build} # added this
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @restaurant = Restaurant.find(params[:recipe][:restaurant_id])
    @recipe = @restaurant.recipes.create(params[:recipe])
    #@recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  # POST
  # POST
  def vote_up
    @recipe = Recipe.find(params[:id])
    if current_user.voted_up_for? @recipe
      respond_to do |format|
        format.html {redirect_to @user}
        format.json {render status: :not_modified, json: {success: false}}
        format.js
      end
    else
      current_user.likes @recipe
      respond_to do |format|
        format.html {redirect_to @user}
        format.json {render status: :ok, json: {success: true}}
        format.js
      end
    end
  end

  def show_users_upvoted
    @recipe = Recipe.find(params[:id])
    @votes = @recipe.up_votes.page(params[:page]).per(params[:perPage])
    @voters = @votes.voters
    respond_to do |format|
      format.json { render 'show_users_upvoted' }
    end    
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper

  def is_new?(recipe)
    recipe.created_at > 21.days.ago.utc
  end

  def is_starred?(recipe)
    numLikes = recipe.votes.size

    totalRestaurantLikes = like_count(recipe.restaurant.recipes)

    return (numLikes.to_f / totalRestaurantLikes) > 0.10
  end

  def is_starred_with?(recipe, totalRestaurantLikes)
    numLikes = recipe.votes.size

    return (numLikes.to_f / totalRestaurantLikes) > 0.10
  end  

  def is_liked_by_current_user?(recipe)
    return current_user.voted_up_for?(recipe) if current_user
    return false
  end
end

app/views/recipes/_form.html.haml
= simple_form_for(@recipe, :html => {:class => 'form-vertical', :multipart => true}) do |f|
  = f.error_notification

  %legend
    = f.input :name
    = f.hidden_field :restaurant_id, :value => @restaurant.id if @restaurant.present?
    = f.input :description, as: :string
    = f.input :category_list, as: :string, label: "Food categories/types", hint: 'Example : Italian, vegetarian ...'
    = f.input :alert_list, as: :string, label: "Food/Allergy alerts", hint: "Example : gluten, meat, ..."
    = f.input :taste_list, as: :string , label: "Dominating Food tastes", hint: 'Example : spicy, sour ...'

  = f.simple_fields_for :recipe_images do |builder|
    %legend
      = builder.label :caption, "Image Caption"
      = builder.text_field :caption
      = builder.label :photo, "Image File"
      = builder.file_field :photo
      - unless builder.object.new_record? 
        = image_tag builder.object.photo.url(:small)


  = f.button :submit

app/views/recipes/_like.html.haml
= simple_form_for(recipe, :url => like_recipe_path(recipe), :html => {:method => :post}, :remote => true) do |f| 
  = image_submit_tag "thumb_up_icon_grey.png", :class => "icon"

app/views/recipes/_recipe-card-for-restaurant.html.haml
%div.recipe-card
  %div.photo
    = link_to image_tag(recipe.recipe_images.first.photo.url(:medium)), recipe
    %div.overlay
    %div.photo-label
      = recipe.name
  %div.recipe-stats
    = render 'recipes/stats-for-restaurants', :recipe => recipe, :restaurant => @restaurant
    

app/views/recipes/_recipe-card.html.haml
%div.recipe-card
  %div.photo
    = link_to image_tag(recipe.recipe_images.first.photo.url(:medium)), recipe
    %div.overlay
    %div.photo-label
      = recipe.name
  %div.recipe-stats
    = render 'recipes/stats', :recipe => recipe

app/views/recipes/_stats-for-restaurants.html.haml
%div.likes
  %div{:id => "recipe-#{recipe.id}-liked"}
    - if user_signed_in? && current_user.liked?(recipe)
      = image_tag "thumb_up_icon_color.png", :class => "icon"
    - else
      = render 'recipes/like', :recipe => recipe

  %span.stat{:id => "recipe-#{recipe.id}-likes"}
    == #{recipe.likes.size}

%div.restaurant-card
  = link_to restaurant.name, restaurant

%div.food-category
  %span
    = recipe.category_list.first if recipe.category_list.any?
%div.food-alert
  %span
    = recipe.alert_list.first if recipe.alert_list.any?
%div.food-taste
  %span
    = recipe.taste_list.first if recipe.taste_list.any?
%div.clearfix

app/views/recipes/_stats.html.haml
%div.likes
  %div{:id => "recipe-#{recipe.id}-liked"}
    - if user_signed_in? && current_user.liked?(recipe)
      = image_tag "thumb_up_icon_color.png", :class => "icon"
    - else
      = render 'recipes/like', :recipe => recipe

  %span.stat{:id => "recipe-#{recipe.id}-likes"}
    = #{recipe.likes.size}
%div.restaurant-card
  = link_to recipe.restaurant.name, recipe.restaurant    
%div.food-category
  %span
    = recipe.category_list.first if recipe.category_list.any?
%div.food-alert
  %span
    = recipe.alert_list.first if recipe.alert_list.any?
%div.food-taste
  %span
    = recipe.taste_list.first if recipe.taste_list.any?
%div.clearfix

app/views/recipes/edit.html.haml
%h2 Editing recipe
%b 
  = @restaurant.name if @restaurant.present?

%div.well
  = render 'form'

= link_to 'Show', @recipe
\|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%div
  %h4 Recipes
= form_tag recipes_path, method: :get do
  .field
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil
%div.recipe-groups
  - @recipes.each do |recipe|
    = render "recipes/recipe-card", :recipe => recipe

app/views/recipes/index_and_edit.html.haml
%h2 Listing recipes

%table.table
  %tr
    %th Name
    %th Image
    %th Image
    %th Image
    - if user_signed_in?
      %th
      %th

  - @recipes.each do |recipe|
    %tr
      %td= link_to recipe.name, recipe
      %td= image_tag recipe.recipe_images.first.photo.url(:small)
      %td
        - if recipe.recipe_images.second.present?
          = image_tag recipe.recipe_images.second.photo.url(:small)
      %td
        - if recipe.recipe_images.third.present?
          = image_tag recipe.recipe_images.third.photo.url(:small) 
      - if user_signed_in? && current_user == recipe.restaurant.user
        %td= link_to 'Edit', edit_recipe_path(recipe)
        %td= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }

%br

/! - if user_signed_in?
/!   = link_to 'New Recipe', new_recipe_path

app/views/recipes/new.html.haml
%h2 
  == #{"New recipe for " + @restaurant.name}

%div.well
  = render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p#notice= notice

%h4
  = @recipe.name

- if user_signed_in? && current_user == @recipe.restaurant.user
  %div
    = link_to 'Edit', edit_recipe_path(@recipe)

%p
  = link_to @recipe.restaurant.name, @recipe.restaurant

  - @recipe.recipe_images.each do |image|
    - if image.present?
      %div
        %div.photo
          = image_tag image.photo.url(:large) 

app/views/recipes/vote_up.js.erb
$('#recipe-<%= @recipe.id %>-likes').html('<%= "#{@recipe.likes.size}" %>');
$('#recipe-<%= @recipe.id %>-liked').html('<%= image_tag "thumb_up_icon_color.png", :class => "icon"%>');