config/routes.rb
DigMenu::Application.routes.draw do

  devise_for :users

  namespace :api do
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
      delete 'users/sign_out' => 'sessions#destroy'
    end

    resources :recipes do
      member do
        post '/vote_up' => 'recipes#vote_up'
      end
    end
  end

  resources :users do
    member do
      get :following, :followers, :liked_recipes, :liked_restaurants
    end
  end

  resources :followships,  :only => [:create, :destroy]

  get "admin/show"

  resources :restaurants do
    member do
      get '/recipes' => 'restaurants#show_recipes'
      get '/users_upvoted' => 'restaurants#show_users_upvoted'
      post '/vote_up' => 'restaurants#vote_up'
    end
  end
  
  resources :recipes do
    member do
      post '/like' => 'recipes#vote_up'
      get '/users_upvoted' => 'recipes#show_users_upvoted'      
      post '/vote_up' => 'recipes#vote_up'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :authentications

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :authentication_token,
    :password_confirmation, :remember_me, :provider, :uid
  attr_accessible :avatar

  acts_as_voter
  acts_as_tagger

  has_many :followships, :foreign_key => "follower_id",
                         :dependent   => :destroy
  has_many :reverse_followships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Followship"                         
  has_many :following, :through => :followships, 
                       :source => :followed
  has_many :followers, :through => :reverse_followships,
					             :source => :follower

  has_many :restaurants                     
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "/assets/avatars/:style/default_user.png"

  #validates_attachment_presence :avatar

  paginates_per 10

  before_save :ensure_authentication_token

  def following?(followed)
    followships.find_by_followed_id(followed)
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if data == "false"
      self.new
    elsif user = self.find_by_email(data.email)
      user
    else # Create a user with a stub password. 
      self.create!(:email => data.email, :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def follow!(followed)
    followships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    followships.find_by_followed_id(followed).destroy
  end

  def avatar_url
    avatar.url(:thumb)
  end

  def avatar_medium_url
    avatar.url(:medium)
  end  

  #def as_json(options = nil)
  #  hash = serializable_hash(options)
  #end

  def serializable_hash(options={})
    options = {
      :only => [:id, :name, :authentication_token]
    }.update(options)
    super(options)
  end
  
  #def Self.liked_restaurants(user)
  #  return nil
  #end

  def self.liked_recipes(user)
    voted_recipes = User.find_by_sql("Select * from votes where voter_id = #{user.id}")
    return voted_recipes
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_for_mobile

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.page(params[:page]).per(params[:perPage])
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.find_up_voted_items
    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @user}
    end    
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(params[:perPage])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(params[:perPage])
    render 'show_follow'
  end

  def liked_recipes
    @user = User.find(params[:id])
    @votes = @user.get_up_voted(Recipe).page(params[:page]).per(params[:perPage])

    respond_to do |format|
      format.json { render 'show_upvote' }
    end
  end

  def liked_restaurants
    @user = User.find(params[:id])
    @votes = @user.get_up_voted(Restaurant).page(params[:page]).per(params[:perPage])
    
    respond_to do |format|
      format.json { render 'show_upvote' }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def current_user_following(followed)
    if current_user
      follow = current_user.following?(followed)
      return follow if follow
    end
    return ""
  end

end

app/views/users/_follow.html.haml
= form_for(current_user.followships.build(:followed_id => @user.id), :remote => true) do |f| 
  %div
    = f.hidden_field :followed_id 
  %div.actions
    = f.submit "Follow"

app/views/users/_follow_form.html.haml
- unless current_user == @user
  %div#follow_form
    - if current_user.following?(@user)
      = render 'users/unfollow'
    - else
      = render 'users/follow'

app/views/users/_stats.html.haml
- @user ||= current_user
%div.stats
  %table{ :summary => "User stats" }
    %tr
      %td
        = link_to following_user_path(@user) do
          %span.stat#following
            == #{@user.following.count} following
      %td
        = link_to followers_user_path(@user) do
          %span.stat#followers
            = pluralize(@user.followers.count, "follower")

app/views/users/_unfollow.html.haml
= form_for(current_user.followships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true) do |f|
  %div.actions
    = f.submit "Unfollow"

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%div
  = image_tag @user.avatar.url(:thumb)
%p
  == #{@user.name}
%p
  == #{@user.email if @user.email}
%p
  = render 'users/follow_form'
  = render 'users/stats'
%p
%h3 Restaurants Liked

%p
%h3 Recipes Liked
%ul.liked_recipes
  %div.recipe-groups
    - @recipes.each do |recipe|
      = render "recipes/recipe-card", :recipe => recipe
  %div.clearfix

app/views/users/show_follow.html.haml
%div.container-fluid
  %div.row-fluid
    %div.span4.well
      %div
        = image_tag @user.avatar.url(:medium)
      %p
        == #{@user.name}
      %p
        == #{@user.email if @user.email}
      = render 'users/stats'
    
    %div.span8.well
      %h4
        == #{@title}
      - if @users.any?
        - @users.each do |user|
          %div
            = image_tag user.avatar.url(:thumb)
            = link_to user.name, user