config/routes.rb
DigMenu::Application.routes.draw do

  devise_for :users

  namespace :api do
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
      delete 'users/sign_out' => 'sessions#destroy'
    end

    resources :recipes do
      member do
        post '/vote_up' => 'recipes#vote_up'
      end
    end
  end

  resources :users do
    member do
      get :following, :followers, :liked_recipes, :liked_restaurants
    end
  end

  resources :followships,  :only => [:create, :destroy]

  get "admin/show"

  resources :restaurants do
    member do
      get '/recipes' => 'restaurants#show_recipes'
      get '/users_upvoted' => 'restaurants#show_users_upvoted'
      post '/vote_up' => 'restaurants#vote_up'
    end
  end
  
  resources :recipes do
    member do
      post '/like' => 'recipes#vote_up'
      get '/users_upvoted' => 'recipes#show_users_upvoted'      
      post '/vote_up' => 'recipes#vote_up'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :category, :address, :city, :country, :region, :description, :name
  attr_accessible :restaurant_images_attributes
  attr_accessible :avatar

  acts_as_votable
  acts_as_gmappable
  
  belongs_to :user
  has_many :recipes, :dependent => :destroy
  #has_many :restaurant_images, :dependent => :destroy
  #accepts_nested_attributes_for :restaurant_images, :reject_if => proc { |attributes| attributes['photo'].blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :category_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :alert_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true
  #accepts_nested_attributes_for :taste_list, :reject_if => proc { |attributes| attributes.blank? }, :allow_destroy => true
  #, :reject_if => lambda { |r| r['restaurant_image'].nil? }

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "/assets/avatars/:style/default_restaurant.png"

  geocoded_by :location
  after_validation :geocode # auto-fetch coordinates
  
  #validates_attachment_presence :avatar

  paginates_per 10

  def avatar_url
    avatar.url(:thumb)
  end

  def avatar_medium_url
    avatar.url(:medium)
  end
  
  #def serializable_hash(options = {})
  #  super(:include => [:restaurant, :recipe_images])
  #end

  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.city}, #{self.country}" 
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :show_recipes]
  before_filter :check_for_mobile

  #respond_to :json

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @json = @restaurant.to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
  def vote_up
    @restaurant = Restaurant.find(params[:id])
    current_user.likes @restaurant
    respond_to do |format|
      format.html {redirect_to @restaurant, notice: "#{@restaurant.name} liked" }
      format.js
    end
  end

  # POST /restaurants/1/vote_up
  # POST /restaurants/1/vote_up.json
  def vote_up
    @restaurant = Restaurant.find(params[:id])
    if current_user.voted_up_for? @restaurant
      respond_to do |format|
        format.html {redirect_to @user}
        format.json {render status: :not_modified, json: {success: false}}
        format.js
      end
    else
      current_user.likes @restaurant
      respond_to do |format|
        format.html {redirect_to @user}
        format.json {render status: :ok, json: {success: true}}
        format.js
      end
    end
  end

  def show_users_upvoted
    @restaurant = Restaurant.find(params[:id])
    @votes = @restaurant.up_votes.page(params[:page]).per(params[:perPage])
    @voters = @votes.voters
    respond_to do |format|
      format.json { render 'show_users_upvoted' }
    end    
  end

  # GET /restaurants/1/recipes
  # GET /restaurants/1/recipes.json
  def show_recipes
    @restaurant = Restaurant.find(params[:id])
    @recipes = @restaurant.recipes.page(params[:page]).per(params[:perPage])
    respond_to do |format|
      format.json { render 'show_recipes' }
    end
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def like_count(recipes)
    numLikes = 0
    recipes.each do |recipe|
      numLikes = numLikes + recipe.likes.count
    end

    return numLikes
  end

  def starred_recipe_count(restaurant)
    totalRestaurantLikes = like_count(restaurant.recipes);
    starredCount = 0;

    restaurant.recipes.each do |recipe|
      if is_starred_with?(recipe, totalRestaurantLikes)
        starredCount = starredCount + 1;
      end
    end
    
    return starredCount;
  end

  def is_liked_by_current_user?(restaurant)
    return current_user.voted_up_for?(restaurant) if current_user
    return false
  end
end

app/views/restaurants/_actions.html.haml
%div.restaurant-actions
  - if user_signed_in? && current_user == @restaurant.user
    = link_to 'Edit', edit_restaurant_path(@restaurant)
    \|
    = link_to 'New Recipe', {:controller => "recipes", :action => "new", :restaurant_id => @restaurant.id}
    \|
  = link_to 'Back', restaurants_path

app/views/restaurants/_form.html.haml
= simple_form_for(@restaurant, :html => {:class => 'form-vertical', :multipart => true}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description, as: :string
    = f.input :country, as: :select, collection: ["CANADA","UNITED STATES"]
    = f.input :region, label: "Province/State"
    = f.input :address 
    = f.input :category



  .form-actions
    = f.button :submit

app/views/restaurants/_property.html.haml
%div.restaurant-property
  %h4
    = @restaurant.name
  %p
    = @restaurant.location
  %p
    %b Category:
    = @restaurant.category

app/views/restaurants/_stats.html.haml
%ul.restaurant-stats
  %li 
    %strong
      = @restaurant.recipes.count
    %span recipes
  %li
    %strong
      = @restaurant.recipes.count
    %span starred
  %li
    %strong
      = total_likes @restaurant.recipes 
    %span likes    
      = like_count @restaurant.recipes   

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

%div.well
  = render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
%h1 Listing restaurants

= form_tag restaurants_path, method: :get do
  .field
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil
%table.table.table-striped
  %tr
    %th Name
    %th Location
    %th Category
    - if user_signed_in?
      %th
      %th

  - @restaurants.each do |restaurant|
    %tr
      %td= link_to restaurant.name, restaurant
      %td= restaurant.location
      %td= restaurant.category
      - if user_signed_in?
        %td= link_to 'Edit', edit_restaurant_path(restaurant)
        %td= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }

%br

- if user_signed_in?
  = link_to 'New Restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice
%div 
  = render "property"
  = render "stats"
  = render "actions"
  = gmaps4rails(@json)
%div.recipe-groups
  %ul
  - @restaurant.recipes.each do |recipe|
    %li
      = render "recipes/recipe-card-for-restaurant", :recipe => recipe
  %div.clearfix
= stylesheet_link_tag 'gmaps4rails'