config/routes.rb
DigMenu::Application.routes.draw do

  devise_for :users

  namespace :api do
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
      delete 'users/sign_out' => 'sessions#destroy'
    end

    resources :recipes do
      member do
        post '/vote_up' => 'recipes#vote_up'
      end
    end
  end

  resources :users do
    member do
      get :following, :followers, :liked_recipes, :liked_restaurants
    end
  end

  resources :followships,  :only => [:create, :destroy]

  get "admin/show"

  resources :restaurants do
    member do
      get '/recipes' => 'restaurants#show_recipes'
      get '/users_upvoted' => 'restaurants#show_users_upvoted'
      post '/vote_up' => 'restaurants#vote_up'
    end
  end
  
  resources :recipes do
    member do
      post '/like' => 'recipes#vote_up'
      get '/users_upvoted' => 'recipes#show_users_upvoted'      
      post '/vote_up' => 'recipes#vote_up'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.pull-right.wat-cf
    %li
      = link_to 'Restaurants', '/restaurants'
    %li
      = link_to 'Recipes', '/recipes'
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method => 'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', admin_show_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Web App
    = stylesheet_link_tag 'web_app_theme'
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = analytics_init :local => Rails.env.development? 

  %body
    #container
      #header
        %h1
          %a{:href => "/"} DigMenu
        #user-navigation
          %ul.nav.pull-right.wat-cf
            %li
              = link_to 'Restaurants', '/restaurants'
            %li
              = link_to 'Recipes', '/recipes'
            %li
              |
            - if user_signed_in?
              %li
                = link_to 'Logout', destroy_user_session_path, :method => 'delete'
            - else
              %li
                = link_to 'Login', new_user_session_path
            - if user_signed_in?
              %li
                = link_to 'Profile', user_path(current_user)
              - if current_user.has_role? :admin
                %li
                  = link_to 'Admin', admin_show_path
            - else
              %li
                = link_to 'Sign up', new_user_registration_path
        #main-navigation
          %ul.wat-cf
    #main{:role => "main"}
      .container
        .content
          = render 'layouts/messages'
          = yield 
          = yield :scripts
          %div.clearfix
        %footer
      / ! end of .container
    / ! end of #main